dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarcloud"

language: python
python:
    - "2.7"
    - "3.5"
install: pip install pipenv && pipenv install
env:
  global:
    - TRAVIS_BUILD=true
script:
    - coverage run --append manage.py test
    - sonar-scanner
branches:
  only:
      - master
      - develop
after_success:
    - coveralls
