version: '3.6'

services:
  db:
    restart: unless-stopped
    image: postgres:9.6-alpine
    volumes:
      - ./compose/db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - db-network
  broker:
    restart: unless-stopped
    image: redis:4.0-alpine
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - 6379:6379
    networks:
      - broker-network
  web:
    restart: unless-stopped
    build: .
    command: >
      sh -c "python3 manage.py migrate --no-input
      && python3 runserver 0.0.0.0:9000"
    volumes:
      - .:/BLST
    ports:
      - 9000:9000
    networks:
      - db-network
      - broker-network
    environment:
      - DB_HOST=db
      - SECRET=${SECRET}
      - DATABASE_URL=postgres://${DB_USER}:${DB_USER_PASSWORD}@${DB_HOST}/blst
      - SOCIAL_AUTH_TWITTER_KEY=${SOCIAL_AUTH_TWITTER_KEY}
      - SOCIAL_AUTH_TWITTER_SECRET=${SOCIAL_AUTH_TWITTER_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - db
      - broker
volumes:
  redis_data:
networks:
  db-network:
  broker-network:
